In [1]:
import numpy as np

an_array = np.array([3,33,333])   #create a rank 1 array  #vector form
#[] (single square bracket) is a vector i.e. having only 1 quantity
print(type(an_array))         #The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
print(an_array)

[  3  33 333]


In [3]:
# test the shape of the array we just created, it should have just one dimension.
print(an_array.shape)  #vector or single dimension

(3,)


In [4]:
# because this is a 1-rank array, we need only one index to access each element.
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [5]:
an_array[0] = 888   # ndarrays are mutable, here we change an element of array.
print(an_array)

[888  33 333]


In [6]:
#[[]] (double square bracket) is a matrix i.e. rows and columns
an_array2 = np.array([[3,33,333]])
print(an_array2.shape)

(1, 3)


In [7]:
another = np.array([[11,12,13],[21,22,23]])  # create a rank 2 array
print(another)   # print the array
print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0,0], ", ",another[0,1],", ",another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


In [8]:
# create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [9]:
# create a 2x2 array filled with 9.0
ex2 = np.full((3,3), 9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [10]:
#create a 2x2 matrix with diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [11]:
# create an array of ones
ex4 = np.ones((2,1))
print(ex4)

[[1.]
 [1.]]


In [12]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

#which means we need to use two indexes to access an element
print()
print(ex4[0,0])

(2, 1)

1.0


In [13]:
# create an array of random floats between 0 & 1
ex5 = np.random.random((2,3))
print(ex5)

[[0.11860159 0.8927432  0.01931632]
 [0.06000497 0.44253063 0.79126771]]


# Slicing

In [14]:
import numpy as np

# Rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
a_slice = an_array[0:2, 1:3]  #[rows range - select 0,1 rows , columns range - select 1,2 columns]
# select 0 and 1 rows, 1 and 2 columns
print(a_slice)

[[12 13]
 [22 23]]


In [16]:
print("Before:", an_array[0,1])  #inspect the element at 0,1
a_slice[0,0] = 1000   # a_slice[0,0] is the same piece of data as an_array[0,1]
print(a_slice[0,0])
print(a_slice)

Before: 12
1000
[[1000   13]
 [  22   23]]


We are making changes in a_slice and printing vlaues of an_array we can see that there has been changes in an_array also

In [17]:
print("After:", an_array[0,1])
print(an_array)

After: 1000
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


# Rank 

(Important)

In [18]:
#Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]   # Rank 1 view #[rows, columns]
print(row_rank1, row_rank1.shape) # notice only a single [] (vector)

[21 22 23 24] (4,)


In [19]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]   # Rank 2 view
print(row_rank2, row_rank2.shape)   # notice the [[]] (matrix)

[[21 22 23 24]] (1, 4)


In [20]:
column_rank1 = an_array[:, 1]   # Rank 1 view  #[rows, columns]
print(column_rank1, column_rank1.shape)

[1000   22   32] (3,)


In [21]:
column_rank2 = an_array[:, 1:2]   # Rank 2 view
print(column_rank2, column_rank2.shape)

[[1000]
 [  22]
 [  32]] (3, 1)


# Indices

In [22]:
# Create a new array
an_array = np.array([[11,12,13],[21,12,23],[31,32,33],[41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 12 23]
 [31 32 33]
 [41 42 43]]


In [23]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)


Col indices picked :  [0 1 2 0]


In [24]:
row_indices = np.arange(4)  # arange will select 0, 1, 2, 3 
print('\nRows indices picked : ', row_indices)


Rows indices picked :  [0 1 2 3]


In [118]:
row_indices = np.arange(4)  # arange will select 0, 1, 2, 3 
print('\nRows indices picked : ', row_indices)


Rows indices picked :  [0 1 2 3]


In [25]:
# Examine the pairings of row_indices and col_indices. These are the elements
for i,j in zip(row_indices, col_indices):
    print(i, ",",j)
'''
for i in row_indices:
for j in col_indices:
'''

0 , 0
1 , 1
2 , 2
3 , 0


'\nfor i in row_indices:\nfor j in col_indices:\n'

In [26]:
# Select one element from each row
print('Values in the array at those indices: ', an_array[row_indices, col_indices])
#an_array[0, 0], an_array[1,1],an_array[2, 2], an_array[3,0] = an_array[row_indices, col_indices]

Values in the array at those indices:  [11 12 33 41]


In [27]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000 # a = a +10 is same as a+=10

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100012     23]
 [    31     32 100033]
 [100041     42     43]]


# Boolean Indexing

In [28]:
# create a 3x2 array
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [29]:
# create a filter which will be boolean values for whether each element meets 
filter = (an_array >15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [30]:
greater = (an_array <20)
greater

array([[ True,  True],
       [False, False],
       [False, False]])

In [31]:
# We can now select just those elements which meet that criteria
print(an_array[filter])  #values that are greater than 15.

[21 22 31 32]


In [32]:
# For short, we could have just used the approach below without the need for 
print(an_array[an_array > 15])

[21 22 31 32]


In [33]:
an_array[an_array % 2 == 0] += 100  # a+=100 is same as a=a+100

print('\nChanged Array:')
print(an_array)


Changed Array:
[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Slicing

In [34]:
# list slicing
a=[2,3,6,7,8,9]
for i in range(2,4,1):
    print(a[i])

6
7


In [35]:
a=[2,3,6,7,8,9]
print(a[2:4])

[6, 7]


In [36]:
b=[9,18,26,45,77,89]
print(b[4:])

[77, 89]


In [37]:
# array slicing
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [38]:
a_slice = an_array[0:2, 2:] 
print(a_slice)

[[13 14]
 [23 24]]


In [39]:
a = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [40]:
s = a[0:2, 1:3] # [0th and 1st rows, 1st and 2nd columns]
print(s)

[[12 13]
 [22 23]]


In [41]:
s = a[0:2, 2:] # [0th and 1st rows, 2nd till end columns]
print(s)

[[13 14]
 [23 24]]


In [42]:
s = a[1:, 2:] # [1st till end rows, 2nd till end columns]
print(s)

[[23 24]
 [33 34]]


# Data types

In [43]:
ex1 = np.array([11, 12]) # Python assigns the data type
print(ex1.dtype)

int32


In [44]:
ex2 = np.array([11.0, 12.0]) # Python assigns the data type
print(ex2.dtype)

float64


In [45]:
ex3 = np.array([11, 21], dtype=np.int64)  # you can also tell Python the data type
print(ex3.dtype)

int64


In [46]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [47]:
ex5 = np.array([11.1,12.7], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11.1 12.7]


# Arithmetic Array Operations

In [48]:
import numpy as np
x = np.array([[111,112],[121,122]],dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


<ipython-input-48-2d342708cfa8>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[111,112],[121,122]],dtype=np.int)


In [49]:
#add
print(x + y)   # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [50]:
#multiply
print(x * y)   # The * sign works
print()
print(np.multiply(x, y))  # so does the numpy function "multiply"

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [51]:
#substract
print(x - y)   # The - sign works
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [52]:
#division
print(x / y)   # The / sign works
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [53]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [54]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Mean & Median

In [55]:
# setup a random 2 X 5 matrix
arr = 10 * np.random.randn(2,5) #random.random or random.randn or random.randint
print(arr)

[[ -0.40987906  -2.99679842   6.63913074   2.80001548   7.79157318]
 [ -7.32647574   1.12245514 -14.35051959   1.86488298   6.4152644 ]]


In [56]:
# compute the mean for all elements
print(arr.mean())

0.15496491105184135


In [57]:
# compute the means by row
print(arr.mean(axis = 1))

[ 2.76480838 -2.45487856]


In [58]:
# compute the means by column
print(arr.mean(axis = 0))

[-3.8681774  -0.93717164 -3.85569443  2.33244923  7.10341879]


In [59]:
# sum all the elements
print(arr.sum())

1.5496491105184136


In [60]:
# compute the medians
print(np.median(arr, axis = 1)) # by rows 1st and 2nd also

[2.80001548 1.12245514]


In [61]:
# compute the medians
print(np.median(arr, axis = 0)) # by columns

[-3.8681774  -0.93717164 -3.85569443  2.33244923  7.10341879]


# Sorting

In [62]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)
print(unsorted)

[ 0.4859888   0.43510783 -0.53827252  0.72474275  0.52878148 -2.48974634
 -0.9371717  -0.44642325 -1.134916   -0.1612471 ]


In [63]:
# create copy and sort
sorted = np.array(unsorted)  # store unsorted in sorted variable
sorted.sort() # it will arrange values in ascending order i.e. sorting
print(sorted)
print()
print(unsorted)

[-2.48974634 -1.134916   -0.9371717  -0.53827252 -0.44642325 -0.1612471
  0.43510783  0.4859888   0.52878148  0.72474275]

[ 0.4859888   0.43510783 -0.53827252  0.72474275  0.52878148 -2.48974634
 -0.9371717  -0.44642325 -1.134916   -0.1612471 ]


In [64]:
# inplace sorting
unsorted.sort()
print(unsorted)

[-2.48974634 -1.134916   -0.9371717  -0.53827252 -0.44642325 -0.1612471
  0.43510783  0.4859888   0.52878148  0.72474275]


# Finding unique elements

In [65]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))  # it will return unique values

[1 2 4]


# Set Operations

In [66]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [67]:
print(np.intersect1d(s1, s2)) # common values between s1 and s2

['bulb' 'chair']


In [68]:
print(np.union1d(s1, s2))  # common and uncommon values between s1 and s2

['bulb' 'chair' 'desk' 'lamp']


In [69]:
print(np.setdiff1d(s1, s2))  # elements in s1 that are not in s2

['desk']


In [70]:
print(np.setdiff1d(s2, s1))  # elements in s2 that are not in s1

['lamp']


In [71]:
print(np.in1d(s1, s2))   # which elements of s1 is also in s2

[False  True  True]


In [72]:
print(np.in1d(s2, s1))   # which elements of s2 is also in s1

[False  True  True]


# Broadcasting

Addition

In [73]:
import numpy as np

start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [74]:
#create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [75]:
y = start + add_rows # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [76]:
# craete an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([0,12,3]) #print(add_cols)
add_cols =add_cols.T
print(add_cols)

[ 0 12  3]


In [77]:
# add to each column of 'start' using broadcasting
y= start + add_cols
print(y)

[[ 0. 12.  3.]
 [ 0. 12.  3.]
 [ 0. 12.  3.]
 [ 0. 12.  3.]]


In [78]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
array1 = np.array([[2,3,4,5],[3,4,5,6],[4,5,6,6]])
array2 = np.array([2,3,4,6])
print("array1:\n",array1)
print("array2:\n",array2)

array1:
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 6]]
array2:
 [2 3 4 6]


In [80]:
add = array1 + array2
print("addition of array1 nd array2: ")
print(add)

addition of array1 nd array2: 
[[ 4  6  8 11]
 [ 5  7  9 12]
 [ 6  8 10 12]]


First setup parameters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [81]:
from numpy import arange
from timeit import Timer #n

size = 1000000
timeits = 1000

In [82]:
# create the ndarray with valtype()ues 0,1,2,...,size-1
nd_array = arange(size) # arange(4), arange(1000000)  10L
print(type(nd_array))

<class 'numpy.ndarray'>


In [83]:
# timer expects the  operation as a parameter,
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" %
     (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000459 seconds


In [84]:
# create the list with values 0,1,2,..., size-1
a_list = list(range(size)) # range(end)  1000000
print(type(a_list))

<class 'list'>


In [85]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list: %f seconds" %
     (timer_list.timeit(timeits)/timeits))   # llist takes more time than array.

Time taken by list: 0.023727 seconds


Binary Format:

In [86]:
import numpy as np
x = np.array([23.23, 24.24])

In [87]:
np.save('an_array',x) #saves the values of an_array in x

In [88]:
np.load('an_array.npy')  # to retrive saved elements from save

array([23.23, 24.24])

Dot product on Matrices and Inner Product on Vectors:

In [89]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])
print("x2d=\n",x2d)
print("y2d=\n",y2d)
print()
print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

x2d=
 [[1 1]
 [1 1]]
y2d=
 [[2 2]
 [2 2]]

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [90]:
# determine the inner product of two vectors 
a1d = np.array([9, 9])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [91]:
# dot produce on an array and vector
print(x2d.dot(a1d))  #([9,9]), ([[1,1],[1,1]]) [1*9, 1*9 + 1*9] = [18, 18], [18, 18]
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


Sum:

In [92]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))   # add all members

66


In [93]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [94]:
# random array
x = np.random.randn(8)
x

array([ 0.29825958, -1.7816841 ,  0.58038762,  0.53113876,  0.96866199,
       -1.25961791,  0.43721718,  0.64911728])

In [95]:
# another random array
y = np.random.randn(8)
y

array([-0.29717058, -1.3203835 ,  0.99222589,  0.06611528, -0.18894772,
       -1.42196745, -0.23614904, -0.88619254])

In [96]:
# return element wise maximum between two arrays
import numpy as np
x = np.random.randn(8)
print("x=",x)
y = np.random.randn(8)
print("y=",y)
print("maximum=", np.maximum(x, y))

x= [ 0.58683556 -0.47801528  0.82493804 -0.48654745 -0.50493589  0.84984043
  0.04584119  1.32659222]
y= [ 2.26922019 -1.57008111  0.0457129   1.92138802  0.49877513 -1.16330694
  0.77930204 -0.2185507 ]
maximum= [ 2.26922019 -0.47801528  0.82493804  1.92138802  0.49877513  0.84984043
  0.77930204  1.32659222]


Reshape:

In [97]:
# grab values from 0 thrpugh 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [98]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)  # 5,4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Transpose:

In [99]:
trans=arr.reshape(4,5).T
print(trans)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


filter using .where():

In [100]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])
# where we have true in filter it will print x_1 value and for false y_1 value
# this is the working of .where function
filter = np.array([True, False, True, False, True])

In [101]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


mat()

In [102]:
mat = np.random.rand(5,5) #mat() is used to interpret a given input as a matrix.
mat

array([[0.62963615, 0.60289626, 0.44771746, 0.05040053, 0.57552765],
       [0.70680509, 0.38631868, 0.1687714 , 0.24499127, 0.97819119],
       [0.15787271, 0.93919476, 0.60862973, 0.70332097, 0.01469652],
       [0.09374397, 0.11816237, 0.63081648, 0.35152479, 0.42365993],
       [0.4915388 , 0.30121965, 0.08509333, 0.8029322 , 0.06473911]])

In [103]:
np.where(mat > 0.5, 1000, -1)

array([[1000, 1000,   -1,   -1, 1000],
       [1000,   -1,   -1,   -1, 1000],
       [  -1, 1000, 1000, 1000,   -1],
       [  -1,   -1, 1000,   -1,   -1],
       [  -1,   -1,   -1, 1000,   -1]])

In [104]:
'''
if mat > 0.5:
    replace(1000)
else:
    replace(-1)
'''

'\nif mat > 0.5:\n    replace(1000)\nelse:\n    replace(-1)\n'

In [105]:
arr_bools = np.array([True, False, True, True, False])

In [106]:
arr_bools.any()  # is any value True

True

In [107]:
arr_bools.all()  # are all values True

False

Random number generation:

In [108]:
import numpy as np
Y = np.random.normal(size = (1,5))
print(Y)

[[1.10336125 0.57098275 0.70413314 0.75673884 1.61218209]]


In [109]:
Z = np.random.randint(low=2,high=50,size=4)  # randint for integer values
print(Z)

[11 42 10 22]


In [110]:
np.random.permutation(Z)  # return a new ordering of elements in Z

array([42, 22, 10, 11])

In [111]:
np.random.uniform(size=4)  #uniform distribution

array([0.01245345, 0.71468255, 0.75612639, 0.44474949])

In [112]:
np.random.normal(size=4) #normal distribution

array([ 0.33201208, -0.19197542, -0.21663515,  1.15975509])

Merging data sets:

In [113]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2, high=50, size=(2,2))
print(M)

[[19  4]
 [46 48]]

[[39  8]
 [32 26]]


In [114]:
np.vstack((K,M))  # join vertically

array([[19,  4],
       [46, 48],
       [39,  8],
       [32, 26]])

In [115]:
np.hstack((K,M))  # join horizontally

array([[19,  4, 39,  8],
       [46, 48, 32, 26]])

In [116]:
np.concatenate([K, M], axis = 0)  # columnwise

array([[19,  4],
       [46, 48],
       [39,  8],
       [32, 26]])

In [117]:
np.concatenate([K, M.T], axis = 1)  #rowwise

array([[19,  4, 39, 32],
       [46, 48,  8, 26]])